spring:
  application:
    name: delivery-service
  threads:
    virtual:
      enabled: true  # Java 21 Virtual Threads

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
