apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: zipkin
          urlDisplayLabel: "View in Zipkin"

  - name: Zipkin
    uid: zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    isDefault: false
    editable: false
