spring:
  application:
    name: order-service

  threads:
    virtual:
      enabled: true  # Java 21 Virtual Threads — giúp Feign call đồng bộ không block OS thread

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  # ============================================================
  # THÊM CẤU HÌNH DATABASE VÀO ĐÂY
  # ============================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: false

server:
  port: 8083

eureka:
  client:
    enabled: false

logging:
  level:
    com.fooddelivery.order: DEBUG