spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/food-delivery-config
          default-label: main
          search-paths: '{application}'
          clone-on-start: true

server:
  port: 8888

logging:
  level:
    com.fooddelivery: DEBUG
    org.springframework.cloud: DEBUG