spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/${CUSTOMER_DB_NAME:customer_db}
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

app:
  internal:
    gateway-secret: ${INTERNAL_GATEWAY_SECRET:test-gateway-secret}
  kafka:
    enabled: false

eureka:
  client:
    enabled: false

logging:
  level:
    com.fooddelivery: DEBUG
